# -*- coding: utf-8 -*-
"""Resume_Job_Matching_v3 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EsNWiT_IviR9YgAiI15_LdQe9--R25AV

# Resume–Job Matching — Data Cleaning & Feature Engineering
One clean top-to-bottom pipeline. Run all cells in order.
"""

!pip install plotly ipywidgets -q

"""## 1. Imports"""

import pandas as pd
import plotly.express as px
import ipywidgets as widgets
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re, ast
from collections import Counter
from datetime import datetime
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 200)
print("Libraries loaded ✔")

"""## 2. Load Raw Data"""

file_path = "/content/sample_data/resume_data.csv"   # ← update if needed
df = pd.read_csv(file_path, encoding='utf-8')
print("Raw shape:", df.shape)
df.head(2)

"""## 3. Fix Column Names"""

df.columns = (df.columns
               .str.replace('\ufeff', '', regex=False)
               .str.replace('ï»¿',    '', regex=False)
               .str.strip()
               .str.lower())
print(df.columns.tolist())

"""## 4. Drop Garbage Columns
These columns are either 100% null, all placeholder text, or carry zero useful signal:
- `educational_results`, `age_requirement` — 100% null  
- `proficiency_levels` — 92% null  
- `locations` — all `'City, State'` placeholders, no real data  
- `result_types` — mostly `[None]` / `['N/A']`  
- `company_urls`, `online_links` — all None/N/A  
- `extra_curricular_organization_links` — all None/N/A
"""

drop_cols = [
    'educational_results',
    'age_requirement',
    'proficiency_levels',
    'locations',
    'result_types',
    'company_urls',
    'online_links',
    'extra_curricular_organization_links',
]
df.drop(columns=drop_cols, errors='ignore', inplace=True)
print("Remaining columns:", df.shape[1])
print(df.columns.tolist())

"""## 5. Replace 'Unknown' / Placeholder Strings with NaN
The string `'Unknown'` was used as a fill value — it needs to become `NaN` so
we can properly detect what's missing and build accurate binary flags.
"""

# All tokens that mean "no real value"
NULL_TOKENS = {
    'unknown', 'n/a', 'na', 'none', 'null', '', ' ',
    'not specified', '[none]', "['n/a']", '[n/a]',
    'city, state', 'city , state',
}

def is_null_value(val):
    if pd.isna(val):
        return True
    return str(val).strip().lower() in NULL_TOKENS

for col in df.columns:
    if df[col].dtype == object:
        mask = df[col].apply(is_null_value)
        if mask.sum() > 0:
            print(f"  {col:<45} nullified {mask.sum()} rows")
            df.loc[mask, col] = np.nan

print("\nNull replacement done ✔")
print("Missing values now:")
print(df.isnull().sum()[df.isnull().sum() > 0])

"""## 6. Binary Presence Flags
Create `has_<col>` flags **after** nullifying unknowns so flags are accurate.
Then keep only non-redundant ones (perfectly correlated flags removed).
"""

flag_cols = [
    'address', 'career_objective', 'languages',
    'extra_curricular_activity_types',
    'certification_providers',
]

for col in flag_cols:
    if col in df.columns:
        df[f'has_{col}'] = df[col].notna().astype(int)

# Drop perfectly-correlated duplicates (correlation = 1.00 with activity_types)
drop_redundant = [
    'extra_curricular_organization_names',  # identical to has_extra_curricular_activity_types
    'extra_curricular_organization_links',  # identical
    'role_positions',                       # identical
    'has_role_positions',                   # if already created
    'certification_skills',                 # identical to has_certification_providers
    'issue_dates',                          # identical
    'expiry_dates',                         # identical
]
df.drop(columns=drop_redundant, errors='ignore', inplace=True)

print("Flags created:", [c for c in df.columns if c.startswith('has_')])
print("Flag value counts:")
for col in [c for c in df.columns if c.startswith('has_')]:
    print(f"  {col:<45} 1s={df[col].sum()}  0s={(df[col]==0).sum()}")

"""## 7. Parse List-Like Columns
Skills, positions, degrees etc. come as either:
- Plain comma strings: `"Python,Java,SQL"`  
- Stringified lists: `"['Python', 'Java']"`

Both formats parsed into proper Python lists.
"""

JUNK_VALUES = {'none', 'nan', 'n/a', 'unknown', '', ' ', 'not specified'}

def to_clean_list(val):
    """Convert any format to a clean Python list of strings, handling newlines and commas."""
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return []

    if isinstance(val, list):
        # If it's already a list, process each item, joining by comma first
        temp_s = ','.join(str(item).replace('\n', ',') for item in val)
    else:
        # If it's a string, replace newlines with commas for consistent parsing
        temp_s = str(val).strip().replace('\n', ',')

    if temp_s.lower() in JUNK_VALUES or not temp_s.strip(): # Check for empty or junk after replacement
        return []

    # Attempt ast.literal_eval if it looks like a list or tuple representation
    try:
        parsed = ast.literal_eval(temp_s)
        if isinstance(parsed, (list, tuple)): # <--- MODIFIED HERE to handle tuples as well
            # If successfully parsed as a list or tuple, process its elements
            all_sub_items = []
            for item in parsed:
                s_item = str(item).strip()
                # Split elements of the parsed list/tuple further by comma
                all_sub_items.extend([i.strip() for i in s_item.split(',') if i.strip().lower() not in JUNK_VALUES])
            return [item for item in all_sub_items if item] # Filter out empty strings
        # If ast.literal_eval returns a single non-list/non-tuple item (e.g., 'skill_name')
        return [str(parsed).strip()] if str(parsed).strip().lower() not in JUNK_VALUES else []
    except (ValueError, SyntaxError):
        pass # Not a stringified list/tuple, proceed with simple split

    # Fallback to splitting by comma (already handled newlines)
    return [i.strip() for i in temp_s.split(',')
            if i.strip().lower() not in JUNK_VALUES and i.strip()] # Filter out empty strings

list_cols = [
    'skills', 'degree_names', 'educational_institution_name',
    'professional_company_names', 'positions',
    'related_skils_in_job', 'major_field_of_studies',
    'educational_requirements', 'experiencere_requirement', 'skills_required',
    'certification_providers', 'certification_skills',
    'languages',
]

for col in list_cols:
    if col in df.columns:
        df[col] = df[col].apply(to_clean_list)

# Sanity check
print("Sample row 0 skills:", df['skills'].iloc[0][:5])
print("Sample row 3 positions:", df['positions'].iloc[3])
print("Sample row 1 degrees:", df['degree_names'].iloc[1])

# Replace empty lists with NaN for columns where emptiness matters
for col in list_cols:
    if col in df.columns:
        empty_pct = (df[col].apply(lambda x: len(x) == 0)).mean() * 100
        print(f"  {col:<45} empty lists: {empty_pct:.1f}%")

"""## 8. Parse Date Columns → Experience Features
Handles all messy formats seen in the data:
- Bare years: `"2019"`, `"2015,2018"`
- Month-year: `"Nov 2019"`, `"June 2018"`, `"Jan 2019"`
- Present tokens: `"Till Date"`, `"Current"`, `"till date"`
- Missing: `""`, `"N/A"` → NaT
"""

TODAY = pd.Timestamp.now()
PRESENT_TOKENS = {'present','till date','current','till now','ongoing','date','now','till date'}

def parse_date_str(s):
    """Parse a single date string to Timestamp."""
    if pd.isna(s): return pd.NaT
    s = str(s).strip().lower()
    if s in PRESENT_TOKENS: return TODAY
    if s in ('', 'n/a', 'none', 'nan', 'unknown'): return pd.NaT
    # bare 4-digit year
    if re.fullmatch(r'\d{4}', s):
        return pd.Timestamp(f'{s}-01-01')
    try:
        ts = pd.to_datetime(s, errors='coerce')
        return ts if pd.notna(ts) else pd.NaT
    except Exception:
        return pd.NaT

def parse_date_col(val):
    """Parse a raw date cell (string or list) into a list of Timestamps."""
    if isinstance(val, list):
        tokens = val
    elif pd.isna(val):
        return []
    else:
        # comma-separated or single value
        tokens = [t.strip() for t in str(val).split(',')]
    results = [parse_date_str(t) for t in tokens]
    return [r for r in results if pd.notna(r)]

# Parse all date columns
for col in ['passing_years', 'start_dates', 'end_dates', 'issue_dates', 'expiry_dates']:
    if col in df.columns:
        df[col + '_parsed'] = df[col].apply(parse_date_col)

# ── Total years of experience ─────────────────────────────────────────────────
def total_experience(starts, ends):
    total = 0.0
    for s, e in zip(starts, ends):
        if pd.notna(s) and pd.notna(e) and e > s:
            total += (e - s).days / 365.25
    return round(total, 2)

df['total_years_experience'] = df.apply(
    lambda r: total_experience(
        r.get('start_dates_parsed', []),
        r.get('end_dates_parsed', [])
    ), axis=1)

# ── Recency of education ──────────────────────────────────────────────────────
def education_recency(years_list):
    valid = [d.year for d in years_list if pd.notna(d)]
    return (TODAY.year - max(valid)) if valid else np.nan

df['recency_education_years'] = df['passing_years_parsed'].apply(education_recency)

# ── Certification status ──────────────────────────────────────────────────────
def cert_status(expires):
    active = expired = False
    for e in expires:
        if pd.notna(e):
            if e >= TODAY: active = True
            else: expired = True
    return 'Active' if active else ('Expired' if expired else 'Unknown')

if 'expiry_dates_parsed' in df.columns:
    df['certification_status'] = df['expiry_dates_parsed'].apply(cert_status)

# ── Sanity check ──────────────────────────────────────────────────────────────
nonzero_exp = (df['total_years_experience'] > 0).sum()
print(f"total_years_experience > 0:  {nonzero_exp} / {len(df)} rows ({nonzero_exp/len(df)*100:.1f}%)")
print(df['total_years_experience'].describe().round(2))
print(f"\nrecency_education_years non-null: {df['recency_education_years'].notna().sum()}")
print(df['recency_education_years'].describe().round(2))

"""## 9. Drop Original Raw Date Columns"""

df.drop(columns=['passing_years','start_dates','end_dates','issue_dates','expiry_dates'],
        errors='ignore', inplace=True)
print("Shape after dropping raw date cols:", df.shape)

"""## 10. Clean Remaining Text Columns
- Strip encoding garbage (`ï¼`, `ï»¿` etc.) from text values  
- Standardize `responsibilities` — this is the **job** responsibilities field (only 28 unique values).
  The resume's actual work descriptions were not captured in this dataset.
- Fill remaining NaN text with empty string for safe downstream processing
"""

def clean_text(val):
    if pd.isna(val): return ''
    s = str(val)
    s = re.sub(r'ï\S{1,4}', '', s)   # remove encoding garbage
    s = re.sub(r'\s+', ' ', s).strip()
    return s

# 'educational_requirements' is already handled by to_clean_list, so remove it from text_cols
text_cols = ['career_objective', 'responsibilities', 'responsibilities.1',
             'address', 'job_position_name'] # Removed 'educational_requirements'

for col in text_cols:
    if col in df.columns:
        df[col] = df[col].apply(clean_text)

# Note: responsibilities and responsibilities.1 are the JOB's responsibilities
# (only 28 unique values across 9544 rows) — resume work descriptions are absent
print(f"responsibilities unique values:   {df['responsibilities'].nunique()}")
print(f"responsibilities.1 unique values: {df['responsibilities.1'].nunique()}")
print(f"Are they identical? {(df['responsibilities'] == df['responsibilities.1']).all()}")

"""## 11. Impute Empty Job Description Fields"""

# Empty lists → ['not specified'] so downstream features don't break
for col in ['experiencere_requirement', 'skills_required', 'educational_requirements']:
    if col in df.columns:
        df[col] = df[col].apply(
            lambda x: ['not specified'] if isinstance(x, list) and len(x) == 0 else x
        )
        print(f"'{col}' — not specified: {df[col].apply(lambda x: x == ['not specified']).sum()}")

"""## 12. Fix Outliers"""

# matched_score must be 0–1
if 'matched_score' in df.columns:
    bad = (df['matched_score'] > 1.0).sum()
    print(f"matched_score > 1.0: {bad} rows → clipping")
    df['matched_score'] = df['matched_score'].clip(0, 1)

# Cap experience at 40 years
df['total_years_experience'] = df['total_years_experience'].clip(0, 40)

# Cap education recency at 50 years; fill missing with -1 (unknown)
if 'recency_education_years' in df.columns:
    df['recency_education_years'] = df['recency_education_years'].clip(0, 50)
    df['recency_education_years'].fillna(-1, inplace=True)

print("Outliers fixed ✔")
print(df[['matched_score','total_years_experience','recency_education_years']].describe().round(2))

"""## 13. Drop Duplicates"""

list_columns_to_convert = [
    'skills', 'degree_names', 'educational_institution_name',
    'professional_company_names', 'positions', 'related_skils_in_job',
    'major_field_of_studies', 'educational_requirements',
    'experiencere_requirement', 'skills_required',
    'certification_providers', 'languages',
    'passing_years_parsed', 'start_dates_parsed', 'end_dates_parsed',
    'issue_dates_parsed', 'expiry_dates_parsed'
]

# Convert lists to tuples for hashability
for col in list_columns_to_convert:
    if col in df.columns:
        df[col] = df[col].apply(lambda x: tuple(x) if isinstance(x, list) else x)

before = len(df)
df.drop_duplicates(inplace=True)
print(f"Dropped {before - len(df)} duplicates. Final shape: {df.shape}")

"""## 14. Post-Cleaning Quality Report"""

print("=" * 65)
print("POST-CLEANING DATA QUALITY REPORT")
print("=" * 65)
print(f"Shape: {df.shape}\n")

print("--- List columns: mean items per row & % empty ---")
list_cols_check = ['skills','positions','degree_names','related_skils_in_job',
                   'skills_required','educational_requirements']
for col in list_cols_check:
    if col in df.columns:
        lengths = df[col].apply(lambda x: len(x) if isinstance(x, list) else 0)
        pct_empty = (lengths == 0).mean() * 100
        print(f"  {col:<45} mean={lengths.mean():.1f}  empty={pct_empty:.1f}%")

print("\n--- Date features ---")
for col in ['total_years_experience','recency_education_years']:
    if col in df.columns:
        meaningful = (df[col] > 0).sum()
        print(f"  {col:<45} meaningful rows: {meaningful} ({meaningful/len(df)*100:.1f}%)")

print("\n--- Binary flags ---")
for col in [c for c in df.columns if c.startswith('has_')]:
    print(f"  {col:<45} present: {df[col].sum()} ({df[col].mean()*100:.1f}%)")

print("\n--- Target variable ---")
print(df['matched_score'].describe().round(3))

print("\n--- Remaining NaN in key columns ---")
key_cols = ['skills','positions','related_skils_in_job','responsibilities.1',
            'job_position_name','skills_required','matched_score']
for col in key_cols:
    if col in df.columns:
        n = df[col].isna().sum() if df[col].dtype != object else 0
        print(f"  {col:<45} nulls: {n}")

"""### recency_education_years is 90.7% dead (only 886 meaningful rows)"""

df.drop(columns=['recency_education_years'], inplace=True)

"""### total_years_experience is only 54% relaible"""

df['has_valid_experience'] = (df['total_years_experience'] > 0).astype(int)

"""### skills"""

# Check the content of 'skills_required'
print("Value counts for the first item in 'skills_required' (top 10):")
print(df['skills_required'].apply(lambda x: x[0] if len(x) > 0 else 'EMPTY_LIST').value_counts().head(10))

print("\nDistribution of lengths for 'skills_required' lists:")
print(df['skills_required'].apply(len).value_counts().sort_index())

print("\nSample of 'skills_required' entries where length is 1:")
print(df[df['skills_required'].apply(len) == 1]['skills_required'].head())

"""## 15. EDA

### 15.1 Target: matched_score distribution
"""

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
df['matched_score'].hist(bins=40, ax=axes[0], color='steelblue', edgecolor='white')
axes[0].set_title('matched_score distribution')
axes[0].set_xlabel('Score')
df.boxplot(column='matched_score', ax=axes[1])
axes[1].set_title('matched_score boxplot')
plt.tight_layout(); plt.show()
print(df['matched_score'].describe().round(3))

"""### 15.2 Top skills vs top required skills

### 15.3 Job position distribution
"""

top_jobs = df['job_position_name'].value_counts().head(20)
fig, ax = plt.subplots(figsize=(10, 6))
top_jobs.sort_values().plot(kind='barh', ax=ax, color='coral')
ax.set_title('Job Positions in Dataset')
plt.tight_layout(); plt.show()

"""### 15.5 Has_ flag completeness"""

has_cols = [c for c in df.columns if c.startswith('has_')]
if has_cols:
    means = df[has_cols].mean().sort_values()
    fig, ax = plt.subplots(figsize=(8, max(3, len(has_cols) * 0.5)))
    means.plot(kind='barh', ax=ax, color='teal')
    ax.set_xlabel('Proportion of resumes with this field')
    ax.set_title('Resume Field Completeness')
    ax.axvline(0.5, color='red', linestyle='--', alpha=0.5, label='50%')
    plt.tight_layout(); plt.show()

"""## 16. Matching Feature Engineering
Build features measuring how well each resume matches its job description.

**Available matching signals:**
- `skills` (resume) vs `skills_required` (job) → Jaccard + cosine
- `related_skils_in_job` vs `skills_required` → Jaccard + cosine  
- `positions` vs `job_position_name` → cosine
- `career_objective` vs `responsibilities.1` → cosine
- Count features: num_skills, num_positions, etc.
- Experience: total_years_experience, recency_education_years

**Note:** `responsibilities` == `responsibilities.1` (same column, job-side only).
Resume work descriptions are absent from this dataset.
"""

# ── Helpers ───────────────────────────────────────────────────────────────────
def list_to_str(val):
    """Flatten list to lowercase string for TF-IDF."""
    if isinstance(val, (list, tuple)): # Updated to handle tuples as well
        return ' '.join(str(i).lower() for i in val
                        if str(i).lower() not in ('none','nan','n/a','not specified',''))
    return str(val).lower() if pd.notna(val) else ''

def jaccard(a, b):
    sa = set(list_to_str(a).split())
    sb = set(list_to_str(b).split())
    if not (sa | sb): return 0.0
    return len(sa & sb) / len(sa | sb)

# ── Jaccard overlap features ───────────────────────────────────────────────────
df['skill_jaccard']          = df.apply(lambda r: jaccard(r['skills'], r['skills_required']), axis=1)
df['related_skill_jaccard']  = df.apply(lambda r: jaccard(r['related_skils_in_job'], r['skills_required']), axis=1)
df['position_title_jaccard'] = df.apply(lambda r: jaccard(r['positions'], r['job_position_name']), axis=1)

# ── Count features ─────────────────────────────────────────────────────────────
df['num_skills']         = df['skills'].apply(lambda x: len(x) if isinstance(x, (list, tuple)) else 0) # Updated
df['num_positions']      = df['positions'].apply(lambda x: len(x) if isinstance(x, (list, tuple)) else 0) # Updated
df['num_related_skills'] = df['related_skils_in_job'].apply(lambda x: len(x) if isinstance(x, (list, tuple)) else 0) # Updated
df['num_degrees']        = df['degree_names'].apply(lambda x: len(x) if isinstance(x, (list, tuple)) else 0) # Updated

# ── TF-IDF cosine similarity features ─────────────────────────────────────────
text_pairs = [
    ('skills',               'responsibilities.1', 'skill_vs_jobresp_cos'),
    ('related_skils_in_job', 'responsibilities.1', 'relskill_vs_jobresp_cos'),
    ('positions',            'job_position_name',  'position_vs_jobtitle_cos'),
    ('career_objective',     'responsibilities.1', 'objective_vs_jobresp_cos'),
]

for col_a, col_b, feat in text_pairs:
    if col_a not in df.columns or col_b not in df.columns: continue
    texts_a = df[col_a].apply(list_to_str)
    texts_b = df[col_b].apply(list_to_str)
    tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
    tfidf.fit(pd.concat([texts_a, texts_b]))
    va = tfidf.transform(texts_a)
    vb = tfidf.transform(texts_b)
    df[feat] = [cosine_similarity(va[i], vb[i])[0][0] for i in range(len(df))]
    print(f"  {feat:<40} mean={df[feat].mean():.3f}  non-zero={( df[feat]>0).sum()}")

print("\nFeature engineering done ✔")

"""## 17. Feature Correlation with matched_score"""

feat_cols = [c for c in df.columns if c.endswith(('_jaccard','_cos','_sim'))
             or c in ['num_skills','num_positions','num_related_skills','num_degrees',
                      'total_years_experience'] # 'recency_education_years' removed as it was dropped earlier
             or c.startswith('has_')]

corr = df[feat_cols + ['matched_score']].corr()['matched_score'].drop('matched_score')
corr_sorted = corr.abs().sort_values(ascending=False)

print("Feature correlations with matched_score (by absolute value):")
for feat, val in corr_sorted.items():
    direction = '+' if corr[feat] >= 0 else '-'
    bar = '█' * int(abs(val) * 40)
    print(f"  {feat:<40} {direction}{abs(val):.3f}  {bar}")

fig, ax = plt.subplots(figsize=(8, max(5, len(feat_cols) * 0.4)))
corr.sort_values().plot(kind='barh', ax=ax,
    color=['tomato' if v < 0 else 'steelblue' for v in corr.sort_values()])
ax.axvline(0, color='black', linewidth=0.8)
ax.set_title('Feature Correlation with matched_score')
plt.tight_layout(); plt.show()

"""## 18. Full Correlation Matrix (numeric features only)"""

num_cols = df.select_dtypes(include=np.number).columns
if len(num_cols) > 1:
    corr = df[num_cols].corr()
    plt.figure(figsize=(max(10, len(num_cols)), max(8, len(num_cols) - 2)))
    sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm',
                square=True, linewidths=0.4, linecolor='white')
    plt.title('Correlation Matrix')
    plt.tight_layout(); plt.show()

"""## 19. Sentence Embedding Features
Unlike TF-IDF which needs **exact word matches**, sentence embeddings understand
meaning — so *"Python developer"* ≈ *"software engineer"* even with zero shared words.

**Why this matters here:** Your TF-IDF features had mean similarity of ~0.02 because
resumes and job descriptions use different vocabulary. Embeddings fix this.

**Model used:** `all-MiniLM-L6-v2` — fast (~80 MB), runs on CPU, excellent quality.

```bash
pip install sentence-transformers   # run once if not installed
```

**Features created:**
| Feature | What it measures |
|---|---|
| `sem_full_sim` | Full resume text vs full job description |
| `sem_skills_sim` | Resume skills vs required skills |
| `sem_position_sim` | Past job titles vs target job title |
| `sem_objective_sim` | Career objective vs job responsibilities |
"""

try:
    from sentence_transformers import SentenceTransformer
    from sklearn.metrics.pairwise import paired_cosine_distances
    import numpy as np
    _EMBED_OK = True
except ImportError:
    _EMBED_OK = False
    print("⚠️  sentence-transformers not installed.")
    print("    Run:  pip install sentence-transformers")
    print("    Then re-run this cell.")

if _EMBED_OK:
    # ── Load model ────────────────────────────────────────────────────────────
    print("Loading model (downloads ~80 MB on first run)...")
    embedder = SentenceTransformer('all-MiniLM-L6-v2')
    print("Model loaded ✔")

    # ── Text builders ─────────────────────────────────────────────────────────
    def resume_text(row):
        """All resume content joined into one string."""
        return ' '.join(filter(None, [
            list_to_str(row['skills']),
            list_to_str(row['positions']),
            list_to_str(row['related_skils_in_job']),
            str(row.get('career_objective', '') or ''),
            list_to_str(row.get('degree_names', [])),
            list_to_str(row.get('major_field_of_studies', [])),
        ]))

    def job_text(row):
        """All job description content joined into one string."""
        return ' '.join(filter(None, [
            str(row['responsibilities.1'] or ''),
            str(row['job_position_name'] or ''),
            list_to_str(row['skills_required']),
            list_to_str(row['educational_requirements']),
            list_to_str(row.get('experiencere_requirement', [])),
        ]))

    print("Building text columns...")
    df['_resume_text']    = df.apply(resume_text, axis=1)
    df['_job_text']       = df.apply(job_text,    axis=1)
    df['_skills_text']    = df['skills'].apply(list_to_str)
    df['_req_text']       = df['skills_required'].apply(list_to_str)
    df['_position_text']  = df['positions'].apply(list_to_str)
    df['_jobtitle_text']  = df['job_position_name'].astype(str)
    df['_objective_text'] = df['career_objective'].astype(str).replace('nan','')

    # ── Encode all text columns in one pass ───────────────────────────────────
    # Encode unique texts only — much faster when there are repeated values
    def encode_col(series, label):
        texts = series.fillna('').tolist()
        print(f"  Encoding {label} ({len(texts)} texts)...")
        return embedder.encode(
            texts, batch_size=256,
            show_progress_bar=True,
            convert_to_numpy=True,
            normalize_embeddings=True   # L2-norm → dot product = cosine similarity
        )

    resume_vecs   = encode_col(df['_resume_text'],   'resume')
    job_vecs      = encode_col(df['_job_text'],      'job description')
    skill_vecs    = encode_col(df['_skills_text'],   'skills')
    req_vecs      = encode_col(df['_req_text'],      'required skills')
    pos_vecs      = encode_col(df['_position_text'], 'positions')
    title_vecs    = encode_col(df['_jobtitle_text'], 'job titles')
    obj_vecs      = encode_col(df['_objective_text'],'career objectives')

    # ── Vectorised cosine similarity (dot product on L2-normed vectors) ───────
    # Much faster than row-by-row cosine_similarity calls
    df['sem_full_sim']      = (resume_vecs * job_vecs).sum(axis=1)
    df['sem_skills_sim']    = (skill_vecs  * req_vecs).sum(axis=1)
    df['sem_position_sim']  = (pos_vecs    * title_vecs).sum(axis=1)
    df['sem_objective_sim'] = (obj_vecs    * job_vecs).sum(axis=1)

    # ── Drop temp text columns ─────────────────────────────────────────────────
    temp_cols = [c for c in df.columns if c.startswith('_')]
    df.drop(columns=temp_cols, inplace=True)

    # ── Report ────────────────────────────────────────────────────────────────
    sem_cols = ['sem_full_sim', 'sem_skills_sim', 'sem_position_sim', 'sem_objective_sim']
    print("\n✔ Semantic features created:")
    print(f"  {'Feature':<30} {'Mean':>6}  {'Std':>6}  {'Min':>6}  {'Max':>6}  {'Corr w/ target':>14}")
    print("  " + "-"*75)
    for col in sem_cols:
        corr = df[col].corr(df['matched_score'])
        print(f"  {col:<30} {df[col].mean():>6.3f}  {df[col].std():>6.3f}  "
              f"{df[col].min():>6.3f}  {df[col].max():>6.3f}  {corr:>14.4f}")

    # ── Quick visual ──────────────────────────────────────────────────────────
    fig, axes = plt.subplots(1, 4, figsize=(18, 4))
    for ax, col in zip(axes, sem_cols):
        ax.scatter(df[col], df['matched_score'], alpha=0.2, s=8, color='steelblue')
        ax.set_xlabel(col.replace('sem_','').replace('_sim',''))
        ax.set_ylabel('matched_score')
        corr = df[col].corr(df['matched_score'])
        ax.set_title(f'r = {corr:.3f}')
    plt.suptitle('Semantic Similarity vs matched_score', fontsize=12)
    plt.tight_layout()
    plt.show()

else:
    # Dummy columns so downstream cells don't break
    for col in ['sem_full_sim','sem_skills_sim','sem_position_sim','sem_objective_sim']:
        df[col] = 0.0
    print("⚠️  Dummy columns created (zeros). Install sentence-transformers to get real values.")

"""## 20. Model Training
Train XGBoost, Random Forest, Gradient Boosting, KNN, and SVR.
Now includes semantic embedding features alongside TF-IDF and Jaccard features.
"""

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler
from xgboost import XGBRegressor
import warnings
warnings.filterwarnings('ignore')

# ── Feature set ───────────────────────────────────────────────────────────────
feat_cols = [c for c in df.columns
             if c.endswith(('_jaccard', '_cos', '_sim'))
             or c in ['num_skills', 'num_positions', 'num_related_skills',
                      'num_degrees', 'total_years_experience', 'has_valid_experience']
             or c.startswith('has_')]

# Drop any that are all-zero (e.g. dummy embedding cols if not installed)
feat_cols = [c for c in feat_cols if df[c].std() > 0]

X = df[feat_cols].fillna(0)
y = df['matched_score']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

print(f"Features: {len(feat_cols)}")
print(f"Train: {X_train.shape}  |  Test: {X_test.shape}")
print("\nFeatures used:", feat_cols)

# ── Scale for KNN and SVR ──────────────────────────────────────────────────────
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# ── Define models ─────────────────────────────────────────────────────────────
models = {
    'XGBoost':           XGBRegressor(n_estimators=300, learning_rate=0.05,
                                       max_depth=5, subsample=0.8,
                                       colsample_bytree=0.8, random_state=42, n_jobs=-1),
    'Random Forest':     RandomForestRegressor(n_estimators=300, max_depth=8,
                                                random_state=42, n_jobs=-1),
    'Gradient Boosting': GradientBoostingRegressor(n_estimators=200, learning_rate=0.05,
                                                    max_depth=4, random_state=42),
    'KNN':               KNeighborsRegressor(n_neighbors=7, n_jobs=-1),
    'SVR':               SVR(kernel='rbf', C=2.0, epsilon=0.1),
}

results = {}
predictions = {}

for name, mdl in models.items():
    # KNN and SVR use scaled data
    if name in ('KNN', 'SVR'):
        mdl.fit(X_train_scaled, y_train)
        y_pred_i = mdl.predict(X_test_scaled)
    else:
        mdl.fit(X_train, y_train)
        y_pred_i = mdl.predict(X_test)

    mae_i = mean_absolute_error(y_test, y_pred_i)
    r2_i  = r2_score(y_test, y_pred_i)
    results[name]     = {'MAE': round(mae_i,4), 'R2': round(r2_i,4)}
    predictions[name] = y_pred_i
    print(f"{name:<22}  MAE={mae_i:.4f}  R2={r2_i:.4f}")

perf_df = pd.DataFrame(results).T.sort_values('R2', ascending=False)
print("\n--- Model Performance Summary ---")
print(perf_df)

# ── Actual vs Predicted plots ─────────────────────────────────────────────────
fig, axes = plt.subplots(2, 3, figsize=(18, 10), sharey=True)
axes = axes.flatten()

for ax, (name, y_pred_i) in zip(axes, predictions.items()):
    ax.scatter(y_test, y_pred_i, alpha=0.4, s=15, color='steelblue')
    lims = [y.min(), y.max()]
    ax.plot(lims, lims, 'r--', lw=1.5)
    ax.set_title(f"{name}  R²={results[name]['R2']:.3f}")
    ax.set_xlabel('Actual')
    ax.set_ylabel('Predicted')

axes[-1].set_visible(False)  # hide empty subplot
plt.suptitle('Actual vs Predicted — All Models', fontsize=14, y=1.01)
plt.tight_layout()
plt.show()

# ── Feature importance (XGBoost) ──────────────────────────────────────────────
xgb_model = [m for k,m in models.items() if k == 'XGBoost'][0]
importances = pd.Series(xgb_model.feature_importances_, index=feat_cols).sort_values(ascending=True)

fig, ax = plt.subplots(figsize=(9, max(5, len(feat_cols) * 0.35)))
importances.plot(kind='barh', ax=ax, color='steelblue')
ax.set_title('XGBoost Feature Importance')
ax.set_xlabel('Importance Score')
plt.tight_layout()
plt.show()

print("\nTop 10 most important features:")
print(importances.sort_values(ascending=False).head(10).round(4))

"""## 21. Save Cleaned Dataset"""

# Convert lists back to strings for CSV storage
save_df = df.copy()
for col in save_df.columns:
    if save_df[col].apply(lambda x: isinstance(x, list)).any():
        save_df[col] = save_df[col].apply(
            lambda x: ', '.join(x) if isinstance(x, list) else x)

save_df.to_csv('resume_data_cleaned.csv', index=False)
print(f"Saved resume_data_cleaned.csv — shape: {save_df.shape}")
print("\nFinal columns:")
df.head(10)
for col in save_df.columns:
    print(f"  {col}")

"""# 📊 Resume Matching Dashboard"""

# ==============================
# 📊 RESUME MATCHING DASHBOARD
# ==============================

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import ipywidgets as widgets
from IPython.display import display
import numpy as np

print("📊 Resume Job Matching Dashboard")

# -----------------------------
# FIND YOUR DATAFRAME
# -----------------------------
if 'resume_df' in globals():
    df = resume_df
elif 'df' in globals():
    df = df
elif 'data' in globals():
    df = data
else:
    raise Exception("❌ No dataframe found. Run your data-loading cell first, then run this dashboard cell.")

# -----------------------------
# BASIC PREP
# -----------------------------
numeric_df = df.select_dtypes(include=np.number)

# -----------------------------
# KPI SECTION
# -----------------------------
total_rows = len(df)
total_cols = df.shape[1]
missing_vals = int(df.isnull().sum().sum())

avg_match = 0
if "matched_score" in df.columns:
    avg_match = float(df["matched_score"].mean())

fig_kpi = go.Figure()

fig_kpi.add_trace(go.Indicator(
    mode="number",
    value=total_rows,
    title={"text": "Rows"},
    domain={'x': [0.00, 0.22], 'y': [0, 1]}
))

fig_kpi.add_trace(go.Indicator(
    mode="number",
    value=total_cols,
    title={"text": "Columns"},
    domain={'x': [0.26, 0.48], 'y': [0, 1]}
))

fig_kpi.add_trace(go.Indicator(
    mode="number",
    value=missing_vals,
    title={"text": "Missing"},
    domain={'x': [0.52, 0.74], 'y': [0, 1]}
))

fig_kpi.add_trace(go.Indicator(
    mode="number",
    value=avg_match,
    title={"text": "Avg Match"},
    domain={'x': [0.78, 1], 'y': [0, 1]}
))

fig_kpi.update_layout(height=250, title="Resume Matching Dashboard Overview")
fig_kpi.show()

# -----------------------------
# MATCH SCORE DISTRIBUTION
# -----------------------------
if "matched_score" in df.columns:
    fig1 = px.histogram(
        df,
        x="matched_score",
        nbins=30,
        title="Match Score Distribution"
    )
    fig1.show()
else:
    print("⚠️ Column 'matched_score' not found.")

# -----------------------------
# CORRELATIONS
# -----------------------------
if "matched_score" in numeric_df.columns:
    corr = numeric_df.corr(numeric_only=True)["matched_score"].drop("matched_score").sort_values(ascending=False).head(10)

    fig2 = px.bar(
        x=corr.values,
        y=corr.index,
        orientation='h',
        title="Top Features Correlated with Match Score",
        labels={"x": "Correlation", "y": "Feature"}
    )
    fig2.show()

# -----------------------------
# FEATURE IMPORTANCE
# -----------------------------
if 'xgb_model' in globals():
    try:
        features = numeric_df.drop(columns=["matched_score"], errors="ignore").columns
        importance = xgb_model.feature_importances_

        if len(features) == len(importance):
            imp_df = pd.DataFrame({
                "Feature": features,
                "Importance": importance
            }).sort_values(by="Importance", ascending=False).head(10)

            fig3 = px.bar(
                imp_df,
                x="Importance",
                y="Feature",
                orientation='h',
                title="Top 10 Feature Importance"
            )
            fig3.show()
        else:
            print("⚠️ Feature names and model importances do not match.")
    except Exception as e:
        print(f"⚠️ Could not generate feature importance: {e}")

# -----------------------------
# INTERACTIVE FILTER
# -----------------------------
if "matched_score" in df.columns:
    slider = widgets.FloatSlider(
        value=float(df["matched_score"].min()),
        min=float(df["matched_score"].min()),
        max=float(df["matched_score"].max()),
        step=0.01,
        description='Min Score:',
        continuous_update=False
    )

    output = widgets.Output()

    def update(change=None):
        with output:
            output.clear_output()
            filtered = df[df["matched_score"] >= slider.value]
            display(filtered.head(20))
            print(f"Showing {len(filtered)} rows")

    slider.observe(update, names='value')
    display(slider, output)
    update()